spring.profiles.active: dev
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  name: demo-admin
  serviceName: demo-admin
  productName: demo
  moduleName: admin
  version: 1.0-SNAPSHOT
  description: "业务微服务"

---
spring:
  datasource:
    url: jdbc:mysql://192.168.0.99:3306/honor_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: honor
    password: My,hg1234
    supportUtf8mb4: 1
    initialSize: 50
    minIdle: 50
    maxActive: 150
  profiles: dev
  application:
    name: demo-admin
    serviceName: demo-admin
    productName: demo
    moduleName: admin
    version: 1.0-SNAPSHOT
  cloud:
    config:
      label: master
      discovery:
        enabled: true
        serviceId: demo-configure
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://demo:demo1234@localhost:8888/eureka/

---
spring:
  profiles: prod
  application:
    name: demo-admin
    serviceName: demo-admin
    productName: demo
    moduleName: admin
    version: 1.0-SNAPSHOT
  cloud:
    config:
      label: master
      discovery:
        enabled: true
        serviceId: demo-configure
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://demo:demo1234@eureka.hearglobal.com:10000/eureka/
